import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Abstract Geometric Art",
    description: "Modern geometric patterns in vibrant colors perfect for contemporary spaces.",
    price: 29.99,
    category: "abstract",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviews: 124,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Minimalist Mountain",
    description: "Clean, simple mountain silhouette design for modern minimalist decor.",
    price: 24.99,
    salePrice: 19.99,
    sale: true,
    category: "minimalist",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    reviews: 89,
    createdAt: "2024-01-02T00:00:00Z",
  },
  {
    id: "3",
    title: "Anime Character Collection",
    description: "Popular anime characters in high-quality print, perfect for fans.",
    price: 22.99,
    category: "anime",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviews: 156,
    createdAt: "2024-01-03T00:00:00Z",
  },
  {
    id: "4",
    title: "Inspirational Quote - Dream Big",
    description: "Motivational typography poster to inspire and energize your space.",
    price: 19.99,
    category: "quotes",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviews: 78,
    createdAt: "2024-01-04T00:00:00Z",
  },
  {
    id: "5",
    title: "Vintage Travel Poster",
    description: "Classic vintage-style travel poster with retro aesthetic.",
    price: 34.99,
    category: "vintage",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviews: 92,
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "6",
    title: "Nature Forest Scene",
    description: "Peaceful forest landscape perfect for bringing nature indoors.",
    price: 27.99,
    salePrice: 22.99,
    sale: true,
    category: "nature",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    reviews: 134,
    createdAt: "2024-01-06T00:00:00Z",
  },
  {
    id: "7",
    title: "Abstract Watercolor",
    description: "Flowing watercolor abstract design in soft, calming tones.",
    price: 31.99,
    category: "abstract",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviews: 67,
    createdAt: "2024-01-07T00:00:00Z",
  },
  {
    id: "8",
    title: "Minimalist Line Art",
    description: "Simple line drawing with elegant minimalist aesthetic.",
    price: 21.99,
    category: "minimalist",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviews: 103,
    createdAt: "2024-01-08T00:00:00Z",
  },
  {
    id: "9",
    title: "Anime Landscape",
    description: "Beautiful anime-style landscape with vibrant colors and detail.",
    price: 26.99,
    category: "anime",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    reviews: 187,
    createdAt: "2024-01-09T00:00:00Z",
  },
  {
    id: "10",
    title: "Motivational Quote - Be Yourself",
    description: "Empowering message in beautiful typography design.",
    price: 18.99,
    category: "quotes",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviews: 45,
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "11",
    title: "Vintage Music Poster",
    description: "Retro music-themed poster with classic vinyl record design.",
    price: 29.99,
    category: "vintage",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviews: 76,
    createdAt: "2024-01-11T00:00:00Z",
  },
  {
    id: "12",
    title: "Ocean Waves",
    description: "Serene ocean scene capturing the beauty of coastal waters.",
    price: 25.99,
    category: "nature",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviews: 112,
    createdAt: "2024-01-12T00:00:00Z",
  },
]
